[package]
name = "wycheproof"
version = "0.1.0"
edition = "2018"
authors = ["Jack Lloyd <jack@randombit.net>"]
license = "Apache-2.0"
description = "Wycheproof test vectors"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
base64 = "0.13"
